### ISSUE TITLE
Error cloning into bare repository: RPC failed; result=22, HTTP code = 504

### ISSUE THREAD

**Issue by sanacl** [grimoirelab/grimoirelab#36]
Using `elasticgirl.22` and the ONAP repos (E.g http://gerrit.onap.org/r/dcae/apod/cdap) I've seen this error:

```
2017-11-16 12:11:17,047 - grimoire_elk.arthur - ERROR - Error feeding ocean from git (http://gerrit.onap.org/r/dcae/apod/cdap): git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/http://gerrit.onap.org/r/dcae/apod/cdap-git'...                            
error: RPC failed; result=22, HTTP code = 504  
fatal: The remote end hung up unexpectedly     

Traceback (most recent call last):             
  File "./grimoire_elk/arthur.py", line 130, in feed_backend                                   
    ocean_backend.feed()                       
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed                                    
    for item in items:                         
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backend.py", line 360, in decorator                                                                          
    for data in func(self, *args, **kwargs):   
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 120, in fetch                                                                    
    latest_items)                              
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 141, in __fetch_from_repo                                                        
    repo = self.__create_git_repository()      
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 186, in __create_git_repository                                                  
    repo = GitRepository.clone(self.uri, self.gitpath)                                         
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 763, in clone                                                                    
    cls._exec(cmd, env=env)                    
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 1220, in _exec                                                                   
    raise RepositoryError(cause=cause)         
perceval.errors.RepositoryError: git command - Cloning into bare repository '/home/bitergia/.perceval/repositories/http://gerrit.onap.org/r/dcae/apod/cdap-git'...                            
error: RPC failed; result=22, HTTP code = 504  
fatal: The remote end hung up unexpectedly 
```

**Comment by sanacl** [comment]
Hold your horses, this seems to be a server error.

```
 luis@hogaza  /tmp  git clone http://gerrit.onap.org/r/dcae/apod/cdap                        
Cloning into 'cdap'...                         
warning: redirecting to https://gerrit.onap.org/r/dcae/apod/cdap/                              


error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504 Gateway Time-out
fatal: The remote end hung up unexpectedly
```
