### ISSUE TITLE
Error "is not a Git mirror of repository " found while collecting existent Git data from Github

### ISSUE THREAD

**Issue by sanacl** [grimoirelab/grimoirelab#38]
While trying to retrieve data for Chef repositories, I've discovered we are losing data due to this error.

How to reproduce:
- version: `elasticgirl.22`
- include the git repo https://github.com/chef/chef.git in your projects.json file

```
2017-11-21 19:39:24,148 - grimoire_elk.arthur - ERROR - Error feeding ocean from git (https://github.com/chef/chef.git): directory '/home/bitergia/.perceval/repositories/https://github.com/chef/chef.git-git' is not a Git mirror of reposit
ory 'https://github.com/chef/chef.git'
Traceback (most recent call last):                         
  File "./grimoire_elk/arthur.py", line 116, in feed_backend                                                          
    ocean_backend.feed(latest_items=latest_items)                                                                     
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed                                                           
    for item in items:                                                                                                
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backend.py", line 360, in decorator   
    for data in func(self, *args, **kwargs):                                                                          
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 120, in fetch                                                                                                                    
    latest_items)                                          
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 141, in __fetch_from_repo                                                                                                        
    repo = self.__create_git_repository()                                                                             
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 188, in __create_git_repository                                                                                                  
    repo = GitRepository(self.uri, self.gitpath)                                                                      
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 732, in __init__                                                                                                                 
    raise RepositoryError(cause=cause)    
```

**Comment by sduenas** [comment]
You have to remove that repository from your local directory.
Perceval does not support to work with git working directories anymore. It only works with bare or mirror repos.
