### ISSUE TITLE
Git data is not being collected: 'Name or service not known' error

### ISSUE THREAD

**Issue by sanacl** [grimoirelab/grimoirelab#39]
Using the latest version provided by our Dev team, I'm not able to collect data for the YoctoProject.

How to reproduce:
- use the versions below
- use the repos at https://gitlab.com/Bitergia/c/yoctoproject/sources/blob/master/projects.json

```
2017-11-22 09:28:20,995 - grimoire_elk.arthur - ERROR - Error feeding ocean from git (git://git.openembedded.org/openembedded-core): [Errno -2] Name or service not known                                                                     
Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 116, in feed_backend
    ocean_backend.feed(latest_items=latest_items)
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 120, in fetch
    latest_items)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 146, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 177, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 867, in sync
    pack_name, refs = self._fetch_pack()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.5-py3.4.egg/perceval/backends/core/git.py", line 1012, in _fetch_pack
    fd.write)
  File "/usr/local/lib/python3.4/dist-packages/dulwich-0.18.6-py3.4-linux-x86_64.egg/dulwich/client.py", line 727, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "/usr/local/lib/python3.4/dist-packages/dulwich-0.18.6-py3.4-linux-x86_64.egg/dulwich/client.py", line 814, in _connect
    self._host, self._port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```
**Important**: from the host the command git clone works with the repo git://git.openembedded.org/openembedded-core

This error was found with the version:
```
SORTINGHAT='641dabd71d4f4a23547592a10096240343268bd1'      
GRIMOIREELK='9a69a31a6499402cddb3c622f12dc5d11e490fed'     
PERCEVAL='fcae408a56f16a25f1f62abc6c01b61d2e0dc100'        
KIBITER='f7bf173cb1d79418b9909d877adfb998ce7b52da'         
GRIMOIRELAB_GITHUB_IO='2f71c036020f6873efdd079f4ec2b5f26584cb2b'                                                       
ARTHUR='3efff3311b52222b7d06bf63ce97f8a42572bc06'          
USE_CASES='31ea49ecc28f3e27aa29fddb0e01b7f475069b6a'       
PANELS='ffe73323afe84e491d0b1705e86a7db3588bff38'          
MORDRED='024019f5ee1df7096f91f7b41286cd58e55e6495'         
TRAINING='9df30c3ec955387a423f261bb141f74133bf7ff7'        
PERCEVAL_MOZILLA='423615b9745ab0b0e577701504e46e0f32aab6a3'                                                            
PERCEVAL_PUPPET='9c0d4c72a0e9b3c7c1e3295f72ebe70c5c874084' 
REPORTS='4ad4f7c9d8cd5eb728a95c3a358d8aa339102c75'         
GRIMOIRELAB_TOOLKIT='95d271af32744eb38f73df592f2e0dc5ea97683b'                                                         
PERCEVAL_OPNFV='0bec845df7e17965892dfb1181da0ab1c77168dc'  
GRIMOIRELAB='efd656ff641623e6a639e095f14f38a71cacc094' 
```

**Comment by sduenas** [comment]
This seems to be a problem with Perceval and its integration with dulwich.
