### ISSUE TITLE
Jenkins errored fetching "status_code"

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/grimoirelab#44]
Got the following traceback with the following repo: https://jenkins.opendaylight.org/releng:
```
2017-11-27 22:43:43,149 - grimoire_elk.arthur - ERROR - Error feeding ocean from jenkins (https://jenkins.opendaylight.org/releng): 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/jenkins.py", line 233, in __send_request
    req = requests.get(url)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 519, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 133, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/jenkins.py", line 91, in fetch
    raw_builds = self.client.get_builds(job['name'])
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/jenkins.py", line 223, in get_builds
    return self.__send_request(url_jenkins)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/jenkins.py", line 237, in __send_request
    if e.response.status_code in [408, 410, 502, 503, 504]:
AttributeError: 'NoneType' object has no attribute 'status_code'
```
Using release `elasticgirl.23`

**Comment by acs** [comment]
This issue must be opened in perceval, not here. The error is inside the jenkins backend. Could you open it there @albertinisg ? In any case, it is an error with the upstream server. It can be handled better in the perceval backend for jira, but it can not be fixed (the new client code being developed in perceval will help in doing retries when these errors appears).
