### ISSUE TITLE
Errors in mordred log: git command - 'git <command> [<revision>...] -- [<file>...]'

### ISSUE THREAD

**Issue by CarWizard** [grimoirelab/grimoirelab#595]
Hi! 

Please - take a look on this errors... any idea where the reason and how to fix?

```
2023-05-12 12:33:15,514 - grimoire_elk.elk - ERROR - Error feeding raw from cocom (https://repourl/reponame1.git): git command - 'git <command> [<revision>...] -- [<file>...]'
 (return code: 128)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/grimoire_elk/elk.py", line 203, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.8/site-packages/grimoire_elk/raw/elastic.py", line 234, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.8/site-packages/grimoire_elk/raw/elastic.py", line 250, in feed_items
    for item in items:
  File "/usr/local/lib/python3.8/site-packages/perceval/backend.py", line 316, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/graal/graal.py", line 184, in fetch_items
    for commit in commits:
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 164, in fetch_items
    for commit in commits:
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 259, in parse_git_log_from_iter
    for commit in parser.parse():
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 542, in parse
    for line in self.stream:
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 1057, in log
    for line in self._exec_nb(cmd_log, cwd=self.dirpath, env=self.gitenv):
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 1287, in _exec_nb
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - 'git <command> [<revision>...] -- [<file>...]'
 (return code: 128)
```
```
2023-05-12 19:07:43,785 - grimoire_elk.elk - ERROR - Error feeding raw from colic (https://repourl/reponame2): git command - 'git <command> [<revision>...] -- [<file>...]'
 (return code: 128)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/grimoire_elk/elk.py", line 203, in feed_backend
    ocean_backend.feed(**params)
  File "/usr/local/lib/python3.8/site-packages/grimoire_elk/raw/elastic.py", line 234, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.8/site-packages/grimoire_elk/raw/elastic.py", line 250, in feed_items
    for item in items:
  File "/usr/local/lib/python3.8/site-packages/perceval/backend.py", line 316, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/graal/graal.py", line 184, in fetch_items
    for commit in commits:
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 164, in fetch_items
    for commit in commits:
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 259, in parse_git_log_from_iter
    for commit in parser.parse():
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 542, in parse
    for line in self.stream:
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 1057, in log
    for line in self._exec_nb(cmd_log, cwd=self.dirpath, env=self.gitenv):
  File "/usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py", line 1287, in _exec_nb
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - 'git <command> [<revision>...] -- [<file>...]'
 (return code: 128)
```

_Originally posted by @FixItNowPlease in https://github.com/chaoss/grimoirelab/issues/593#issuecomment-1545982670_

**Comment by zhquan** [comment]
Hi @FixItNowPlease 

Sorry for not getting back to you sooner, I have been very busy these days. Currently `cocom` and `colic` you have to configure the correct branches.

Could you add both branches (`[main, master]`)? Probably you will still have those errors but let's see if Mordred can fetch data when only matches one branch.

To solve that you should create two sections of `cocom` and `colic`
- setup.cfg
```
[cocom:main]
raw_index = cocom_chaoss
enriched_index = cocom_chaoss_enrich
category = code_complexity_lizard_file
studies = [enrich_cocom_analysis]
branches = main

[cocom:master]
raw_index = cocom_chaoss
enriched_index = cocom_chaoss_enrich
category = code_complexity_lizard_file
studies = [enrich_cocom_analysis]
branches = master

[colic:main]
raw_index = colic_chaoss
enriched_index = colic_chaoss_enrich
category = code_license_nomos
studies = [enrich_colic_analysis]
exec-path = /usr/share/fossology/nomos/agent/nomossa
branches = main

[colic:master]
raw_index = colic_chaoss
enriched_index = colic_chaoss_enrich
category = code_license_nomos
studies = [enrich_colic_analysis]
exec-path = /usr/share/fossology/nomos/agent/nomossa
branches = master
```
- projects.json
```
{
    "project": {
        "cocom:main": [
            "repositories with the main branch"
        ],
        "cocom:master": [
            "repositories with the master branch"
        ],
        "colic:main": [
            "repositories with the main branch"
        ],
        "colic:master": [
            "repositories with the master branch"
        ],
    }
}
```
